name: TDengine Docs Typos

on: 
  pull_request:
    branches:
      - 'main'
      - '3.0'
    paths:
      - 'docs/**'

jobs:
  run:
    
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Use custom zh config file
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/zh/**/*.md'
          config: docs/typos.toml

      - name: Use custom en config file
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/en/**/*.md'
          config: docs/typos.toml