name: TDengine Docs Typos

on: [push]

jobs:
  run:
    
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Use custom zh config file
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/zh/**/*.md'
          config: docs/zh/typos_zh.toml

      - name: Use custom en config file
        uses: crate-ci/typos@v1.31.1
        with:
          files: 'docs/en/**/*.md'
          config: docs/en/typos_en.toml