name: TDGpt Update Service

on:
  push:
  schedule:
    - cron: '30 00 * * *'

env:
  WKC: "/root/TDengine"

jobs:
  update-service:
    runs-on:
      group: CI
      labels: [self-hosted, Linux, X64, tdgpt-anode-service]
    steps:
      - name: Update TDengine codes
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}
          git checkout 3.0

      - name: Package the TDGpt Anode Service
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}/tools/tdgpt/script && ./release.sh

      - name: Reinstall and restart the TDGpt Anode Service
        run: |
          set -euo pipefail
          cd ${{ env.WKC }}/tools/tdgpt/release
          if [[ -f "TDengine-enterprise-anode-1.0.1.tar.gz" ]]; then
            tar -xzf TDengine-enterprise-anode-1.0.1.tar.gz
            cd TDengine-enterprise-anode-1.0.1
            ./install.sh
          fi
          systemctl restart taosanoded
